### ISSUE TITLE
对简介章节进行内容贡献

### ISSUE THREAD

**Issue by humleyang** [NilToOne/GenshinGameTheoryDraft#5]
**占用文件：** 元素附着论/1.简介.md
**计划占用时间：** 20220526 17:12 - 20220526 17:20
**计划贡献内容：**
-  进行简介章节的内容贡献。

**Comment by humleyang** [comment]
提交pr： #6  
内容总结：
- 进行简介章节的内容贡献。

**Comment by hypergraphUniverse** [comment]
pr通过，进行交叉审稿

**计划占用时间：** 20220526 17:34 - 20220526 18:00
**计划贡献内容：**
- 尝试将语言风格变得更加通俗易懂
- 增加一些前置概念

**Comment by hypergraphUniverse** [comment]
**提交commit：** [e23a028](https://github.com/NilToOne/GenshinGameTheoryDraft/commit/e23a028aa5c1d7f18ad6da78c66abdc4c5a0a7d7)
**内容总结：** 
- 去除抽象的概念，采取通俗语言风格，加入"为什么要研究元素附着"段落。
- 尝试对某些词汇进行精确的定义，例如"攻击"，"不同攻击"，"元素附着"。

**遗留内容：**
- "不同攻击"精确定义等待补充。
- "元素附着"定义等待补充。

**Comment by humleyang** [comment]
建议对1.1的用语继续打磨，减少学习成本。
可能需要考虑1.1中用语，附着冷却现象对于轻度玩家可能并不“明显”。

**Comment by hypergraphUniverse** [comment]
推荐对1.1中打磨语言的时，尽量描述读者具体能够观察到的现象，让读者能够从现象上意识到这个规则的存在。
例如说元素附着提及“怪物头上出现了元素小图标”

或者说在语言上，提出问题引导读者思考。
例如说“如果深渊法师的水盾由胡桃来破，是不是打上去的每一枪都能削减护盾呢？”
